const projects = [
  {
    name: "First Project",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    tools: "Firebase Node.js Express.js React.js",
    id: 1,
    home: true,
  },
  {
    name: "First Project",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    tools: "Firebase Node.js Express.js React.js",
    id: 2,
    home: true,
  },
  {
    name: "First Project",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    tools: "Firebase Node.js Express.js React.js",
    id: 3,
    home: true,
  },
  {
    name: "First Project",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    tools: "Firebase Node.js Express.js React.js",
    id: 4,
    home: true,
  },
  {
    name: "First Project",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    tools: "Firebase Node.js Express.js React.js",
    id: 5,
    home: true,
  },
  {
    name: "First Project",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    tools: "Firebase Node.js Express.js React.js",
    id: 6,
    home: false,
  },
  {
    name: "First Project",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    tools: "Firebase Node.js Express.js React.js",
    id: 7,
    home: false,
  },
  {
    name: "First Project",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    tools: "Firebase Node.js Express.js React.js",
    id: 8,
    home: false,
  },
  {
    name: "First Project",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    tools: "Firebase Node.js Express.js React.js",
    id: 9,
    home: false,
  },
  {
    name: "First Project",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    tools: "Firebase Node.js Express.js React.js",
    id: 10,
    home: false,
  },
  {
    name: "First Project",
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    tools: "Firebase Node.js Express.js React.js",
    id: 11,
    home: false,
  },
];

export default projects